# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - jobtoapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
    
    - name: Install pre requisits
      run: apt-get update -yq && apt-get install curl gnupg gcc g++ make -yq && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      
    - name: Install yarn
      run: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && apt-get update && apt-get install yarn -yq
    
    - name: Install nodejs and npm
      run: curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs
      
    - name: Restore project
      run: dotnet restore && npm install
      
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jobtoapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8e09255fd206497b847bdb456ab440a7 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
